spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://:3306/springboot_starter
    username: bikash
    password: bikash
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 300000
      refresh-token:
        expiration: 86400000
  user:
    admin:
      first-name: admin
      last-name: admin
      email: admin@mail.com
      password: admin
    manager:
      first-name: manager
      last-name: manager
      email: manager@mail.com
      password: manager
